# Steam Web API的apiKey 大部分功能都需要
# https://partner.steamgames.com/doc/webapi_overview/auth
apiKey: []

# proxy代理 HTTP/SOCKS5代理地址,如Clash: http://127.0.0.1:7890
proxy: ""

# api请求超时时间 单位: 秒
timeout: 5

# 优先使用通用, 再使用指定, 如果填了proxy, 则都会带上proxy请求
# 通用反代 比如填写: https://example.com/{{url}} 则会替换 {{url}} 为实际请求的url
commonProxy: ""

# 主要用的接口
# https://api.steampowered.com 的反代 会替换成对应地址
apiProxy: ""

# steam商城相关的接口
# https://store.steampowered.com 的反代 会替换成对应地址
storeProxy: ""

# steam社区相关的接口
# https://steamcommunity.com/ 的反代 会替换成对应地址
communityProxy: ""
